import { Category, Product } from "@/types"

// ============================================================
// TABLE ZONES & TABLES
// ============================================================

export type TableZone = {
    id: string
    name: string
    sortOrder: number
    isActive: boolean
}

export type FloorTable = {
    id: string
    zoneId: string
    tableNumber: string
    seats: number
    status: "AVAILABLE" | "OCCUPIED" | "RESERVED" | "CLEANING" | "MERGED"
    shape: string
    posX: number
    posY: number
    isActive: boolean
    zone?: TableZone
    currentOrderTotal?: number
    occupiedMinutes?: number
    guestCount?: number
}

export const MOCK_ZONES: TableZone[] = [
    { id: "zone-1", name: "Indoor Tầng 1", sortOrder: 0, isActive: true },
    { id: "zone-2", name: "Outdoor Sân vườn", sortOrder: 1, isActive: true },
    { id: "zone-3", name: "Bar Counter", sortOrder: 2, isActive: true },
    { id: "zone-4", name: "VIP Room", sortOrder: 3, isActive: true },
]

export const MOCK_TABLES: FloorTable[] = [
    // Indoor Tầng 1
    { id: "t-01", zoneId: "zone-1", tableNumber: "T01", seats: 4, status: "AVAILABLE", shape: "square", posX: 0, posY: 0, isActive: true },
    { id: "t-02", zoneId: "zone-1", tableNumber: "T02", seats: 4, status: "OCCUPIED", shape: "square", posX: 1, posY: 0, isActive: true, currentOrderTotal: 850000, occupiedMinutes: 45, guestCount: 3 },
    { id: "t-03", zoneId: "zone-1", tableNumber: "T03", seats: 2, status: "AVAILABLE", shape: "square", posX: 2, posY: 0, isActive: true },
    { id: "t-04", zoneId: "zone-1", tableNumber: "T04", seats: 6, status: "OCCUPIED", shape: "rectangle", posX: 0, posY: 1, isActive: true, currentOrderTotal: 1250000, occupiedMinutes: 72, guestCount: 5 },
    { id: "t-05", zoneId: "zone-1", tableNumber: "T05", seats: 4, status: "RESERVED", shape: "square", posX: 1, posY: 1, isActive: true },
    { id: "t-06", zoneId: "zone-1", tableNumber: "T06", seats: 4, status: "CLEANING", shape: "square", posX: 2, posY: 1, isActive: true },
    // Outdoor
    { id: "t-07", zoneId: "zone-2", tableNumber: "T07", seats: 4, status: "AVAILABLE", shape: "circle", posX: 0, posY: 0, isActive: true },
    { id: "t-08", zoneId: "zone-2", tableNumber: "T08", seats: 4, status: "OCCUPIED", shape: "circle", posX: 1, posY: 0, isActive: true, currentOrderTotal: 430000, occupiedMinutes: 20, guestCount: 2 },
    { id: "t-09", zoneId: "zone-2", tableNumber: "T09", seats: 6, status: "AVAILABLE", shape: "circle", posX: 2, posY: 0, isActive: true },
    // Bar Counter
    { id: "t-10", zoneId: "zone-3", tableNumber: "B01", seats: 1, status: "OCCUPIED", shape: "square", posX: 0, posY: 0, isActive: true, currentOrderTotal: 180000, occupiedMinutes: 15, guestCount: 1 },
    { id: "t-11", zoneId: "zone-3", tableNumber: "B02", seats: 1, status: "AVAILABLE", shape: "square", posX: 1, posY: 0, isActive: true },
    // VIP
    { id: "t-12", zoneId: "zone-4", tableNumber: "VIP1", seats: 8, status: "AVAILABLE", shape: "rectangle", posX: 0, posY: 0, isActive: true },
]

// ============================================================
// MOCK CATEGORIES
// ============================================================

export const MOCK_CATEGORIES: Category[] = [
    {
        id: "cat-1",
        name: "No-fuss Drinks",
        nameVi: "Đồ uống đơn giản",
        icon: "",
        sortOrder: 0,
        isActive: true,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
        _count: { products: 5 },
    },
    {
        id: "cat-2",
        name: "Wine by Bottle",
        nameVi: "Rượu nguyên chai",
        icon: "",
        sortOrder: 1,
        isActive: true,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
        _count: { products: 8 },
    },
    {
        id: "cat-3",
        name: "Wine by Glass",
        nameVi: "Rượu ly",
        icon: "",
        sortOrder: 2,
        isActive: true,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
        _count: { products: 6 },
    },
    {
        id: "cat-4",
        name: "Food",
        nameVi: "Đồ ăn",
        icon: "",
        sortOrder: 3,
        isActive: true,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
        _count: { products: 7 },
    },
    {
        id: "cat-5",
        name: "Dessert",
        nameVi: "Tráng miệng",
        icon: "",
        sortOrder: 4,
        isActive: true,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
        _count: { products: 3 },
    },
]

// ============================================================
// MOCK PRODUCTS
// ============================================================

export const MOCK_PRODUCTS: Product[] = [
    // Wine by Bottle
    {
        id: "prod-1",
        name: "Château Margaux 2018",
        nameVi: null,
        sku: "WB-001",
        categoryId: "cat-2",
        type: "WINE_BOTTLE",
        taxRateId: "tax-10",
        vintage: 2018,
        appellation: "Margaux AOC",
        grapeVariety: "Cabernet Sauvignon, Merlot",
        country: "France",
        region: "Bordeaux",
        alcoholPct: 13.5,
        tastingNotes: "Complex nose of blackcurrant, violet, and cedar. Full-bodied with silky tannins.",
        costPrice: 3500000,
        sellPrice: 5900000,
        glassPrice: null,
        isByGlass: false,
        glassesPerBottle: 0,
        tastingPortions: 0,
        servingTemp: "16-18°C",
        decantingTime: "2h",
        glassType: "Bordeaux",
        oxidationHours: 72,
        trackInventory: true,
        lowStockAlert: 3,
        imageUrl: null,
        description: "One of Bordeaux's finest First Growth estates.",
        isActive: true,
        sortOrder: 0,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
    },
    {
        id: "prod-2",
        name: "Opus One 2019",
        nameVi: null,
        sku: "WB-002",
        categoryId: "cat-2",
        type: "WINE_BOTTLE",
        taxRateId: "tax-10",
        vintage: 2019,
        appellation: "Napa Valley",
        grapeVariety: "Cabernet Sauvignon, Cabernet Franc, Merlot",
        country: "USA",
        region: "California",
        alcoholPct: 14.5,
        tastingNotes: "Rich dark fruit, hints of cocoa and vanilla. Elegant structure.",
        costPrice: 6000000,
        sellPrice: 9800000,
        glassPrice: null,
        isByGlass: false,
        glassesPerBottle: 0,
        tastingPortions: 0,
        servingTemp: "16-18°C",
        decantingTime: "1h",
        glassType: "Bordeaux",
        oxidationHours: 72,
        trackInventory: true,
        lowStockAlert: 2,
        imageUrl: null,
        description: "A Napa Valley icon, collaboration between Mondavi and Rothschild.",
        isActive: true,
        sortOrder: 1,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
    },
    {
        id: "prod-3",
        name: "Cloudy Bay Sauvignon Blanc 2022",
        nameVi: null,
        sku: "WB-003",
        categoryId: "cat-2",
        type: "WINE_BOTTLE",
        taxRateId: "tax-10",
        vintage: 2022,
        appellation: "Marlborough",
        grapeVariety: "Sauvignon Blanc",
        country: "New Zealand",
        region: "Marlborough",
        alcoholPct: 13.0,
        tastingNotes: "Vibrant citrus and passionfruit with herbal undertones.",
        costPrice: 650000,
        sellPrice: 1200000,
        glassPrice: null,
        isByGlass: false,
        glassesPerBottle: 0,
        tastingPortions: 0,
        servingTemp: "8-10°C",
        decantingTime: null,
        glassType: "White wine",
        oxidationHours: 48,
        trackInventory: true,
        lowStockAlert: 5,
        imageUrl: null,
        description: "New Zealand's most iconic Sauvignon Blanc.",
        isActive: true,
        sortOrder: 2,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
    },
    // Wine by Glass
    {
        id: "prod-4",
        name: "Cabernet Sauvignon Glass",
        nameVi: "Ly Cabernet Sauvignon",
        sku: "WG-001",
        categoryId: "cat-3",
        type: "WINE_GLASS",
        taxRateId: "tax-10",
        vintage: null,
        appellation: null,
        grapeVariety: "Cabernet Sauvignon",
        country: null,
        region: null,
        alcoholPct: null,
        tastingNotes: null,
        costPrice: 50000,
        sellPrice: 90000,
        glassPrice: 90000,
        isByGlass: true,
        glassesPerBottle: 8,
        tastingPortions: 0,
        servingTemp: "16-18°C",
        decantingTime: null,
        glassType: "Bordeaux",
        oxidationHours: 72,
        trackInventory: true,
        lowStockAlert: 2,
        imageUrl: null,
        description: "House Cabernet Sauvignon served by the glass.",
        isActive: true,
        sortOrder: 0,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
    },
    {
        id: "prod-5",
        name: "Pinot Noir Glass",
        nameVi: "Ly Pinot Noir",
        sku: "WG-002",
        categoryId: "cat-3",
        type: "WINE_GLASS",
        taxRateId: "tax-10",
        vintage: null,
        appellation: null,
        grapeVariety: "Pinot Noir",
        country: null,
        region: null,
        alcoholPct: null,
        tastingNotes: null,
        costPrice: 60000,
        sellPrice: 120000,
        glassPrice: 120000,
        isByGlass: true,
        glassesPerBottle: 8,
        tastingPortions: 0,
        servingTemp: "14-16°C",
        decantingTime: null,
        glassType: "Burgundy",
        oxidationHours: 72,
        trackInventory: true,
        lowStockAlert: 2,
        imageUrl: null,
        description: "Elegant Pinot Noir, perfect for a quiet evening.",
        isActive: true,
        sortOrder: 1,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
    },
    {
        id: "prod-6",
        name: "Chardonnay Glass",
        nameVi: "Ly Chardonnay",
        sku: "WG-003",
        categoryId: "cat-3",
        type: "WINE_GLASS",
        taxRateId: "tax-10",
        vintage: null,
        appellation: null,
        grapeVariety: "Chardonnay",
        country: null,
        region: null,
        alcoholPct: null,
        tastingNotes: null,
        costPrice: 45000,
        sellPrice: 85000,
        glassPrice: 85000,
        isByGlass: true,
        glassesPerBottle: 8,
        tastingPortions: 0,
        servingTemp: "10-12°C",
        decantingTime: null,
        glassType: "White wine",
        oxidationHours: 48,
        trackInventory: true,
        lowStockAlert: 2,
        imageUrl: null,
        description: "Buttery Chardonnay with hints of oak.",
        isActive: true,
        sortOrder: 2,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
    },
    // No-fuss Drinks
    {
        id: "prod-7",
        name: "Aperol Spritz",
        nameVi: null,
        sku: "DR-001",
        categoryId: "cat-1",
        type: "DRINK",
        taxRateId: "tax-10",
        vintage: null,
        appellation: null,
        grapeVariety: null,
        country: null,
        region: null,
        alcoholPct: 11,
        tastingNotes: null,
        costPrice: 35000,
        sellPrice: 120000,
        glassPrice: null,
        isByGlass: false,
        glassesPerBottle: 0,
        tastingPortions: 0,
        servingTemp: null,
        decantingTime: null,
        glassType: null,
        oxidationHours: null,
        trackInventory: false,
        lowStockAlert: 0,
        imageUrl: null,
        description: "Classic Italian aperitif cocktail.",
        isActive: true,
        sortOrder: 0,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
    },
    {
        id: "prod-8",
        name: "Negroni",
        nameVi: null,
        sku: "DR-002",
        categoryId: "cat-1",
        type: "DRINK",
        taxRateId: "tax-10",
        vintage: null,
        appellation: null,
        grapeVariety: null,
        country: null,
        region: null,
        alcoholPct: 24,
        tastingNotes: null,
        costPrice: 40000,
        sellPrice: 150000,
        glassPrice: null,
        isByGlass: false,
        glassesPerBottle: 0,
        tastingPortions: 0,
        servingTemp: null,
        decantingTime: null,
        glassType: null,
        oxidationHours: null,
        trackInventory: false,
        lowStockAlert: 0,
        imageUrl: null,
        description: "A bold, bitter Italian classic.",
        isActive: true,
        sortOrder: 1,
        createdAt: new Date("2026-03-10"),
        updatedAt: new Date("2026-03-10"),
    },
    {
        id: "prod-14",
        name: "Gin & Tonic",
        nameVi: null,
        sku: "DR-003",
        categoryId: "cat-1",
        type: "DRINK",
        taxRateId: "tax-10",
        vintage: null, appellation: null, grapeVariety: null, country: null, region: null, alcoholPct: 12, tastingNotes: null,
        costPrice: 30000, sellPrice: 110000, glassPrice: null, isByGlass: false, glassesPerBottle: 0, tastingPortions: 0,
        servingTemp: null, decantingTime: null, glassType: null, oxidationHours: null, trackInventory: false, lowStockAlert: 0, imageUrl: null,
        description: "Refreshing gin with premium tonic.", isActive: true, sortOrder: 2,
        createdAt: new Date("2026-03-10"), updatedAt: new Date("2026-03-10"),
    },
    // Food
    {
        id: "prod-9",
        name: "Cheese Board",
        nameVi: "Đĩa Phô mai",
        sku: "FD-001",
        categoryId: "cat-4",
        type: "FOOD",
        taxRateId: "tax-10",
        vintage: null, appellation: null, grapeVariety: null, country: null, region: null, alcoholPct: null, tastingNotes: null,
        costPrice: 80000, sellPrice: 250000, glassPrice: null, isByGlass: false, glassesPerBottle: 0, tastingPortions: 0,
        servingTemp: null, decantingTime: null, glassType: null, oxidationHours: null, trackInventory: true, lowStockAlert: 5, imageUrl: null,
        description: "Selection of imported cheeses with crackers and fruits.",
        isActive: true, sortOrder: 0, createdAt: new Date("2026-03-10"), updatedAt: new Date("2026-03-10"),
    },
    {
        id: "prod-10",
        name: "Cold Cut Board",
        nameVi: "Đĩa Thịt nguội",
        sku: "FD-002",
        categoryId: "cat-4",
        type: "FOOD",
        taxRateId: "tax-10",
        vintage: null, appellation: null, grapeVariety: null, country: null, region: null, alcoholPct: null, tastingNotes: null,
        costPrice: 100000, sellPrice: 320000, glassPrice: null, isByGlass: false, glassesPerBottle: 0, tastingPortions: 0,
        servingTemp: null, decantingTime: null, glassType: null, oxidationHours: null, trackInventory: true, lowStockAlert: 5, imageUrl: null,
        description: "Assorted Italian cold cuts with olives and pickles.",
        isActive: true, sortOrder: 1, createdAt: new Date("2026-03-10"), updatedAt: new Date("2026-03-10"),
    },
    {
        id: "prod-11",
        name: "Bruschetta",
        nameVi: "Bánh mì nướng Ý",
        sku: "FD-003",
        categoryId: "cat-4",
        type: "FOOD",
        taxRateId: "tax-10",
        vintage: null, appellation: null, grapeVariety: null, country: null, region: null, alcoholPct: null, tastingNotes: null,
        costPrice: 35000, sellPrice: 120000, glassPrice: null, isByGlass: false, glassesPerBottle: 0, tastingPortions: 0,
        servingTemp: null, decantingTime: null, glassType: null, oxidationHours: null, trackInventory: true, lowStockAlert: 10, imageUrl: null,
        description: "Toasted bread topped with tomatoes, basil, and olive oil.",
        isActive: true, sortOrder: 2, createdAt: new Date("2026-03-10"), updatedAt: new Date("2026-03-10"),
    },
    {
        id: "prod-12",
        name: "Truffle Fries",
        nameVi: "Khoai tây chiên Truffle",
        sku: "FD-004",
        categoryId: "cat-4",
        type: "FOOD",
        taxRateId: "tax-10",
        vintage: null, appellation: null, grapeVariety: null, country: null, region: null, alcoholPct: null, tastingNotes: null,
        costPrice: 40000, sellPrice: 150000, glassPrice: null, isByGlass: false, glassesPerBottle: 0, tastingPortions: 0,
        servingTemp: null, decantingTime: null, glassType: null, oxidationHours: null, trackInventory: true, lowStockAlert: 10, imageUrl: null,
        description: "Crispy fries with truffle oil and parmesan.",
        isActive: true, sortOrder: 3, createdAt: new Date("2026-03-10"), updatedAt: new Date("2026-03-10"),
    },
    // Dessert
    {
        id: "prod-13",
        name: "Tiramisu",
        nameVi: null,
        sku: "DS-001",
        categoryId: "cat-5",
        type: "FOOD",
        taxRateId: "tax-10",
        vintage: null, appellation: null, grapeVariety: null, country: null, region: null, alcoholPct: null, tastingNotes: null,
        costPrice: 45000, sellPrice: 130000, glassPrice: null, isByGlass: false, glassesPerBottle: 0, tastingPortions: 0,
        servingTemp: null, decantingTime: null, glassType: null, oxidationHours: null, trackInventory: true, lowStockAlert: 5, imageUrl: null,
        description: "Classic Italian coffee-flavored dessert.",
        isActive: true, sortOrder: 0, createdAt: new Date("2026-03-10"), updatedAt: new Date("2026-03-10"),
    },
]
